In [1]:
import sys
import numpy as np

In [2]:
from libs import algorithms as al
%load_ext autoreload
%autoreload 2
from libs import algorithms as al

In [123]:
a = [10, 22, 9, 33, 21, 50, 41, 60]
b = [10,22,9,33,21,50,41,60,80]

c1 = [ 1, 2, -1, 0, 3, 8, 5]
c2 = [0, 3, 7, 8, 13]
c3 = [ 5, 2, -1, 0, 3, 8, 5]

In [18]:
np.sort(c2)

array([ 0,  3,  7,  8, 13])

In [99]:
X = c1
print(X)
Y = []
for i in np.arange(1, len(X)):
    y = X[i] - X[i-1]
    Y.append(y)
print(' ',Y)

[1, 2, -1, 0, 3, 8, 5]
  [1, -3, 1, 3, 5, -3]


In [100]:
Ys = np.sort(Y)
print(Ys)

[-3 -3  1  1  3  5]


In [101]:
l, b = al.LCS(Y, Ys)
print('Len:',l)
print(b.shape)

Len: 4
(6, 6)


In [102]:
idx, lcs = al.calculate_LCS(b,Y,len(Y),len(Y))
idx, lcs

(4, 5) 5
(3, 4) 3
(2, 3) 1
(0, 2) 1


([0, 2, 3, 4], [1, 1, 3, 5])

In [103]:
idx = np.array(idx) + 1
idx

array([1, 3, 4, 5])

In [104]:
np.array(X)[idx]

array([2, 0, 3, 8])

In [124]:
X = c3
print(X)
Y = []
for i in np.arange(1, len(X)):
    y = X[i] - X[i-1]
    Y.append(y)
print(' ',Y)

[5, 2, -1, 0, 3, 8, 5]
  [-3, -3, 1, 3, 5, -3]


In [125]:
Ys = np.sort(Y)
print(Ys)

[-3 -3 -3  1  3  5]


In [126]:
l, b = al.LCS(Y, Ys)
print('Len:',l)
print(b.shape)

Len: 5
(6, 6)


In [127]:
idx, lcs = al.calculate_LCS(b,Y,len(Y),len(Y))
idx, lcs

(4, 5) 5
(3, 4) 3
(2, 3) 1
(1, 2) -3
(0, 1) -3


([0, 1, 2, 3, 4], [-3, -3, 1, 3, 5])

In [128]:
idx = np.array(idx) + 1
idx

array([1, 2, 3, 4, 5])

In [129]:
np.array(X)[idx]

array([ 2, -1,  0,  3,  8])

In [92]:
X = c2
print(X)
Y = []
for i in np.arange(1, len(X)):
    y = X[i] - X[i-1]
    Y.append(y)
print(' ',Y)

[0, 3, 7, 8, 13]
  [3, 4, 1, 5]


In [93]:
Ys = np.sort(Y)
print(Ys)

[1 3 4 5]


In [78]:
l, b = al.LCS(Y, Ys)
print('Len:',l)
print(b.shape)

Len: 3
(4, 4)


In [79]:
idx, lcs = al.calculate_LCS(b,Y,len(Y),len(Y))
idx, lcs

(3, 3) 5
(1, 2) 4
(0, 1) 3


([0, 1, 3], [3, 4, 5])

In [80]:
idx = np.array(idx) + 1
idx

array([1, 2, 4])

In [69]:
np.array(X)[idx]

array([ 3,  7, 13])